#!/usr/bin/env bash

PLAYERS="$(playerctl --list-all)"
IsPlaying=0

[[ -z "${PLAYERS}" ]] && PLAYERS="NotPlaying"

for player in ${PLAYERS}; do
    status_=$(playerctl --player="${player}" status 2>/dev/null)

    if [[ "${status_}" == "Playing" ]]; then
        IsPlaying=1
        break
    fi
done


if [[ $IsPlaying -eq 0 ]]; then
    swaylock --daemonize --image "$HOME/.config/sway/lock_screen/bg.jpg"
    swaymsg 'output * power off'
fi

