call plug#begin('/usr/share/vim/VIM')
    Plug 'tpope/vim-commentary'
    Plug 'preservim/nerdtree'
    Plug 'vim-airline/vim-airline'
    " Plug 'tomsar/molokai'
call plug#end()

colorscheme sorbet
syntax enable
set relativenumber
set termguicolors
set shiftwidth=4
set expandtab
set tabstop=4
set number
filetype plugin indent on

command! RunCPP w | !gcc -x c++ -pedantic -std=c++20 -lstdc++ -fno-elide-constructors -Wall -Wextra -O0 "%" -o "%:r" && ./"%:r" ; rm ./"%:r"
command! RunC w | !gcc -pedantic -Wall -Wextra -O0 "%" -o "%:r" && ./"%:r" ; rm ./"%:r"
command! InstallPlug call InstallPlug()

function! InstallPlug()
    call system("curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim")
endfunction

nnoremap <silent><A-j> :move +1 <CR>==
vnoremap <silent><A-j> :move '>+1 <CR>gv=gv
inoremap <silent><A-j> <ESC>:move +1 <CR>==gi

nnoremap <silent><A-k> :move -2 <CR>==
xnoremap <silent><A-k> :move '<-2 <CR>gv=gv
inoremap <silent><A-k> <ESC>:move -2 <CR>==gi

nnoremap <silent><S-CR> <CMD>normal! o <CR>
nnoremap <silent><F2> :if &wrap <BAR> set nowrap <CR> <BAR> else <BAR> set wrap <CR> <BAR> endif <CR><CR>
nnoremap <silent><C-S-CR> <CMD>normal! O <CR>
nnoremap <silent><C-Space> <CMD>NERDTreeToggle<CR>
cnoremap <silent><C-CR> <INS><CR><ESC>

