#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# ASCII colors
GREEN="\033[38;2;100;255;40m"
YELLOW="\033[38;2;255;190;65m"
BLUE="\033[38;2;100;100;240m"
RED="\033[38;2;255;10;10m"
NC="\033[0m"
HL="\033[1m"

# An array to hold all the given flags
FLAGS_ARRAY=("$@")

# Your git local dotfile repository
GIT_DIR="${HOME}/DEV_DIR/GIT/ConfigFiles"

# Github username and dotfile repository
USERNAME="Alectro-100"
REPO_NAME="Dotfiles"

# command in use to copy stuff
SYNC_="rsync"

# 1 for git status 0 for no git status
GIT_STATUS=0

# LOG=2 INFO=1 ERROR=0
LOG_LEVEL=1

# Toggle push or pull
SHOULD_PUSH=0
SHOULD_CLONE=0

# string '--force'
FORCE=""

# Temporary variable
CLONE_DIR=""
MSG=""

### Files to file Copy
declare -A FILES_TO_COPY=(
    ["${HOME}/.vimrc.bak"]="${GIT_DIR}/vim_config/vimrc"
    ["${HOME}/.config/nvim/init.vim.bak"]="${GIT_DIR}/neovim_config/init.vim"
    ["${HOME}/.SHELL_RC"]="${GIT_DIR}/shell_config/SHELL_RC"
    ["${HOME}/.bashrc"]="${GIT_DIR}/shell_config/bashrc"
    ["${HOME}/.config/foot/foot.ini"]="${GIT_DIR}/sway_config/foot/foot.ini"
)

### Directory to Directory Copy
declare -A DIRS_TO_COPY=(
    ["${HOME}/.config/hypr"]="${GIT_DIR}/hyprland_config"
    ["${HOME}/.config/sway"]="${GIT_DIR}/sway_config"
    ["${HOME}/.config/i3"]="${GIT_DIR}/i3_config"
    ["${HOME}/.config/waybar"]="${GIT_DIR}/waybar_config"
    ["${HOME}/.config/wofi"]="${GIT_DIR}/wofi_config"
    ["${HOME}/.config/qutebrowser"]="${GIT_DIR}/qutebrowser"
    ["${HOME}/.bin"]="${GIT_DIR}/scripts"
)

function INFO() {
    [[ $LOG_LEVEL -ge 1 ]] && {
        echo -e "[${HL}${GREEN}INFO${NC}]: $@"
    } || {
        return 0
    }
}

function ERROR() {
    [[ $LOG_LEVEL -ge 0 ]] && {
        echo -e "[${HL}${RED}ERROR${NC}]: $@"
    } || {
        return 0
    }
}

function DEBUG_LOG() {
    [[ $LOG_LEVEL -ge 2 ]] && {
        echo -e "[${HL}${YELLOW}DEBUG_LOG${NC}]: $@"
    } || {
        return 0
    }
}

function CopyFiles() {
    local SOURCE="$1"
    local DEST="$2"

    if [[ ! -f "${SOURCE}" ]]; then
        ERROR "Source '${BLUE}${SOURCE}${NC}' file does not exist"
        return 1
    fi

    mkdir --parents -- $(dirname "${DEST}")

    if [[ $LOG_LEVEL -ge 2 ]]; then
        if [[ "$SYNC_" == "rsync" ]]; then
            $SYNC_ --progress --archive "${SOURCE}" "${DEST}" || ERROR "Copy failed"
            INFO "Copied '${GREEN}${SOURCE}${NC}' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
        else
            $SYNC_ --verbose "${SOURCE}" "${DEST}" || ERROR "Copy failed"
            INFO "Copied '${GREEN}${SOURCE}${NC}' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
        fi
    else
        if [[ "$SYNC_" == "rsync" ]]; then
            $SYNC_ --archive "${SOURCE}" "${DEST}" 1> /dev/null 2>&1 || ERROR "Copy failed"
            INFO "Copied '${GREEN}${SOURCE}${NC}' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
        else
            $SYNC_ "${SOURCE}" "${DEST}" 1> /dev/null 2>&1 || ERROR "Copy failed"
            INFO "Copied '${GREEN}${SOURCE}${NC}' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
        fi
    fi
}

function CopyDirs() {
    local SOURCE="$1"
    local DEST="$2"

    if [[ ! -d "${SOURCE}" ]]; then
        ERROR "Source '${BLUE}${SOURCE}${NC}' directory does not exist"
        return 1
    fi

    mkdir --parents -- "${DEST}"

    if [[ $LOG_LEVEL -ge 2 ]]; then
        if [[ "$SYNC_" == "rsync" ]]; then
            $SYNC_ --progress --archive "${SOURCE}/" "${DEST}/" || ERROR "Copy failed"
            INFO "Copied '${GREEN}${SOURCE}${NC}/*' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
        else
            $SYNC_ --verbose --recursive "${SOURCE}"/* "${DEST}" || ERROR "Copy failed"
            INFO "Copied '${GREEN}${SOURCE}${NC}/*' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
        fi
    else
        if [[ "$SYNC_" == "rsync" ]]; then
            $SYNC_ --archive "${SOURCE}/" "${DEST}/" 1> /dev/null 2>&1 || ERROR "Copy failed"
            INFO "Copied '${GREEN}${SOURCE}${NC}/*' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
        else
            $SYNC_ --recursive "${SOURCE}"/* "${DEST}" 1> /dev/null 2>&1 || ERROR "Copy failed"
            INFO "Copied '${GREEN}${SOURCE}${NC}/*' ${RED}--->${NC} '${BLUE}${DEST}${NC}'"
        fi
    fi
}

function CloneRepo() {
    local DIR="$1"

    [[ -z "${USERNAME}" ]] && {
        ERROR "No github username given"
    }
    [[ -z "${REPO_NAME}" ]] && {
        ERROR "No github repository name given"
    }

    if [[ -z "${DIR}" ]]; then
        INFO "No directory given. Using your current directory to clone"
        DIR="$(realpath .)"
        cd "${DIR}"
    elif [[ -d "${DIR}" ]]; then
        mkdir -p "${DIR}"
        cd "${DIR}"
    fi
    DEBUG_LOG "Getting dotfile repo from github"
    INFO "Cloning your repository at: $(realpath .)"
    git clone "https://github.com/${USERNAME}/${REPO_NAME}.git" && \
        INFO "Repository clone at '${BLUE}${DIR}${NC}'"
}

function PushRepo() {
    local COMMIT_MSG=""
    local SATISFIED=""

    [[ -z "${USERNAME}" ]] && {
        ERROR "No github username given"
    }
    [[ -z "${REPO_NAME}" ]] && {
        ERROR "No github repository name given"
    }

    cd "${GIT_DIR}"

    if git diff --quiet && git --no-pager diff --quiet --staged; then
        git push "git@github.com:${USERNAME}/${REPO_NAME}.git" $(git symbolic-ref --short HEAD) ${FORCE} && \
            INFO "Successfully pushed your changes to github repository"
    else
        INFO "Launching git interactive git add"
        git add -p || ERROR "Interactive staging failed"
        if [[ -z "${MSG}" ]]; then
            echo -en "Your commit message: "
            read -r COMMIT_MSG
            [[ -z "${COMMIT_MSG}" ]] && {
                ERROR "Empty commit message."
                exit 1
            }
        else
            COMMIT_MSG="${MSG}"
        fi
        INFO "Summary of staged changes"
        git diff --staged --stat
        echo -en "Are you saisfied with changes? (y|n): "
        read -r SATISFIED
        if [[ "${SATISFIED}" =~ ^(y|yes|Yes)$ || "${SATISFIED}" == "" ]]; then
            git commit -m "${COMMIT_MSG}" && INFO "Successfully commited the changes"
        else
            INFO "Commit aborted"
        fi
        git push "git@github.com:${USERNAME}/${REPO_NAME}.git" $(git symbolic-ref --short HEAD) ${FORCE} && \
            INFO "Successfully pushed your changes to github repository"
    fi
}

function Cleanup() {
    ERROR "${RED}Sync interrupted. Clean up manually.${NC}" && exit 1
}

trap Cleanup SIGINT SIGTERM

for (( i=0 ; i < ${#FLAGS_ARRAY[@]} ; i++ )); do
    arg="${FLAGS_ARRAY[$i]}"
    if [[ "$arg" == -* ]]; then
        case "$arg" in
            -v|--verbose|--progress)
                LOG_LEVEL=1
                DEBUG_LOG "Verbose is set"
                ;;
            -l|--log|--loglevel)
                unset LOG_LEVEL
                readonly LOG_LEVEL="${FLAGS_ARRAY[$(( i + 1 ))]:-1}"
                if [[ -z "$LOG_LEVEL" || "$LOG_LEVEL" == -* ]]; then
                    LOG_LEVEL=1
                elif [[ "$LOG_LEVEL" -gt 2 ]]; then
                    DEBUG_LOG "LOG_LEVEL has no effect over integer 2"
                else
                    if [[ $LOG_LEVEL -eq 2 ]]; then
                        DEBUG_LOG "Debugging enabled"
                    fi
                    DEBUG_LOG "LOG_LEVEL: $LOG_LEVEL"
                fi
                i=$(( i + 1 ))
                ;;
            -d|-db|--db|--deb|--debug)
                LOG_LEVEL=2
                DEBUG_LOG "Debugging enabled"
                ;;
            -g|-gs|--gs|--status|--git-status)
                GIT_STATUS=1
                DEBUG_LOG "GIT_STATUS is set"
                ;;
            -c|--clone|--clone-local)
                CLONE_DIR="${FLAGS_ARRAY[$(( i + 1 ))]}"
                [[ -n "${CLONE_DIR}" ]] && {
                    i=$(( i + 1 ))
                }
                SHOULD_CLONE=1
                ;;
            -m|-msg|--msg)
                MSG="${FLAGS_ARRAY[$(( i + 1 ))]}"
                [[ -n "${MSG}" ]] && {
                    i=$(( i + 1 ))
                }
                SHOULD_CLONE=1
                ;;
            -p|--push)
                SHOULD_PUSH=1
                DEBUG_LOG "Backup will be pushed to github"
                ;;
            --force)
                FORCE="--force"
                DEBUG_LOG "Forcing push"
                ;;
            *)
                ERROR "Invalid flag: $arg"
                ;;
        esac
    fi
done


if [[ "${SHOULD_CLONE}" -eq 1 ]]; then
    CloneRepo "${CLONE_DIR}"
    exit 0
fi

if command -v rsync 1> /dev/null 2>&1; then
    SYNC_="rsync"
    [[ $? -ne 0 ]] && ERROR "'rsync' not found. Falling back to 'cp'."
elif command -v cp 1> /dev/null 2>&1; then
    SYNC_="cp"
fi

# Why local dotfile directory doesn't exist
if [[ ! -d "${GIT_DIR}" ]]; then
    mkdir --parents "${GIT_DIR}" || {
        ERROR "Cannot create '${BLUE}${GIT_DIR}${NC}'"
        exit 1
    }
fi

DEBUG_LOG "Using GIT_DIR=$GIT_DIR"
DEBUG_LOG "Using GIT_STATUS=$GIT_STATUS"
DEBUG_LOG "Using LOG_LEVEL=$LOG_LEVEL"
DEBUG_LOG "Using SYNC_=$SYNC_"

echo && INFO "Dotfile directory: ${BLUE}${GIT_DIR}${NC}\n"

# Start copying all the files to the destination
for src in "${!FILES_TO_COPY[@]}"; do
    CopyFiles "${src}" "${FILES_TO_COPY[$src]}"
done

# Start copying directory content to the the destination
for src in "${!DIRS_TO_COPY[@]}"; do
    CopyDirs "${src}" "${DIRS_TO_COPY[$src]}"
done

if [[ ${GIT_STATUS} -eq 1 ]]; then
    cd ${GIT_DIR}
    git status
fi

[[ $SHOULD_PUSH -eq 1 ]] && {
    PushRepo
}

