#!/usr/bin/env bash

FLAG="$1"
TEMP_FILE="/tmp/.cava_instances.tmp"
TIMESTAMP="/tmp/.timestamp_cava_instances.tmp"
speed=0.01
# threshold=0

function KILL_CAVA() {
    kill -INT $(cat "${TEMP_FILE}")
}

function CAVA() {
    for (( i=0 ; i < 8 ; i++ )); do
        footclient --server-socket=/tmp/foot.sock -e "cava" &>/dev/null &
        echo $! >> "${TEMP_FILE}"
        sleep "$speed"
        disown
    done
    date +%s > "${TIMESTAMP}"
}

[[ "${FLAG}" == "CLEAN" ]] && {
    KILL_CAVA
    rm -f "${TEMP_FILE}" "${TIMESTAMP}"
    exit 0
}

# last_time=$(cat "${TIMESTAMP}")
# now=$(date +%s)
# elapsed=$(( now - last_time ))

# if (( elapsed <= threshold )); then
#     KILL_CAVA
# else
#     CAVA
# fi

CAVA
