#!/bin/bash

# Downloads songs from a youtube playlist
# Usage: Download <Playlist-URL>

GREEN="\033[38;2;0;244;0m"
RED="\033[38;2;244;0;0m"
NC="\033[0m"

PLAYLIST_URL="$1"
DOWNLOAD_DIRECTORY="$HOME/Music"
CONCURRENT_DOWNLOADS=4

function INFO() {
    echo -e "[${GREEN}INFO${NC}]: $1"
}

function ERROR() {
    echo -e "[${RED}ERROR${NC}]: $1"
    exit 1
}

if [[ $# -eq 0 ]]; then
    ERROR "No arguments? Ok but at least one URLS?"
fi

if [[ ! -d "${DOWNLOAD_DIRECTORY}" ]]; then
    ERROR "Directory '${DOWNLOAD_DIRECTORY}' doesn't exist"
fi

if [[ -n "${PLAYLIST_URL}" ]]; then
    cd "${DOWNLOAD_DIRECTORY}" || ERROR "Cannot cd into '${DOWNLOAD_DIRECTORY}'"
    # Best audio
    # Title based naming
    # Album art if available
    #
    # Audio preference
    # 1. webm (Opus)
    # 2. m4a (AAC)
    # If neither pick whatever the best
    yt-dlp -f "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio" \
        -N $CONCURRENT_DOWNLOADS \
        --embed-thumbnail --convert-thumbnails jpg \
        --yes-playlist \
        -o "%(title).150s.%(ext)s" \
        "$PLAYLIST_URL"
fi

