#!/bin/bash

[[ $1 == "clear" ]] && clear

result=$(systemctl is-active docker.service 2> /dev/null)

if [[ $result == "inactive" ]] ; then
    sudo systemctl start docker.service
fi

docker start Fedora
docker exec -it Fedora bash -c "cd ~ && exec bash"

