#!/bin/bash

result=$(systemctl is-active docker 2> /dev/null)

if [[ "${result}" == "inactive" ]] ; then
    sudo systemctl start docker
fi

docker start Fedora

[[ $1 =~ ^(clear|cls|cl|c)$ ]] && clear

docker exec -it Fedora bash -c "cd ~ && exec zsh"

