#!/bin/bash

### Default Config ###
SOURCE="/"
DESTINATION="/tmp/MY_DEVICE"

USERNAME="u0_a643"
HOSTNAME="192.168.43.1"
PORT="8022"


### First argument
FLAG="$1"

### Some colors
LITTEL_RED="\033[38;2;200;10;10m"
LITTLE_GREEN="\033[38;2;120;200;85m"
LITTLE_BLUE="\033[38;2;126;117;255m"
BLUE="\033[38;2;152;60;200m"
GREEN="\033[38;2;138;230;81m"
GRAY="\033[38;2;125;125;125m"
ORANGE="\033[38;2;200;64;38m"
PERL_GREEN="\033[1m\033[38;2;0;200;160m"
NC="\033[0m"

### SSH specific variables
CONFIG_FILE="/tmp/.sshfsMountScriptConf"
PRIVATE_KEY="$HOME/.ssh"
SSH_OPTIONS="-oreconnect -oCompression=yes"

### Debug and networking variables
DEBUG=1
# Ping command will wait till NETWORK_TIMEOUT
NETWORK_TIMEOUT=3
# 0 Set's no limit on Mount location 0 > will set the mount location timeout
MOUNT_TIMEOUT=0
# Only changes the permissions for local directory created on local machine
DESTINATION_DIRECTORY_PERMISSION=755

function DEBUG_LOG() {
    if [[ $DEBUG -eq 1 ]]; then
        echo -e "[${ORANGE}DEBUG${NC}]: $1"
    fi
}

function INFO() {
    echo -e "[${LITTLE_GREEN}INFO${NC}]: $1"
}

function ERROR() {
    echo -e "[${LITTEL_RED}ERROR${NC}]: $1"
    if [[ $2 -ne 0 ]]; then
        exit 1
    else
        return 0
    fi
}

function InstallTool() {
    Tool="$1"

    if command -v pacman 1> /dev/null 2>&1; then
        echo "Installing ${Tool} via your package manager."
        sudo pacman -Sy --noconfirm ${Tool}
        exit 0
    elif command -v apt 1> /dev/null 2>&1; then
        echo "Installing ${Tool} via your package manager."
        sudo apt update && sudo apt install -y ${Tool}
        exit 0
    elif command -v dnf 1> /dev/null 2>&1; then
        echo "Installing ${Tool} via your package manager."
        sudo dnf install -y ${Tool}
        exit 0
    elif command -v yum 1> /dev/null 2>&1; then
        echo "Installing ${Tool} via yum."
        sudo yum install -y ${Tool}
        exit 0
    fi
}

function SetTextEditor() {
    if command -v nvim 1> /dev/null 2>&1; then
        EDITOR="nvim"
        return 0
    elif command -v vim  1> /dev/null 2>&1; then
        EDITOR="vim"
        return 0
    elif command -v nano 1> /dev/null 2>&1; then
        EDITOR="nano"
        return 0
    else
        echo "NO text editor found on your system"
        InstallTool "vim"
    fi
}

function Log_Message() {
    showConfig="$1"

    local type="$1"

    if [[ "${UseConfig}" =~ ^(No|no)$ ]]; then
        echo -e "#=========================================================================="
        echo -e "# Config '${LITTLE_BLUE}"${CONFIG_FILE}"${NC}' will be used?: "${UseConfig}""
        echo -e "#=========================================================================="
        echo ""
    fi

    if [[ "${UseConfig}" =~ ^(Yes|yes|true)$ ]]; then
        echo -e "#=========================================================================="
        echo -e "# Configuration file found at '${LITTLE_BLUE}${CONFIG_FILE}${NC}'"
        echo -e "# Config '${LITTLE_BLUE}"${CONFIG_FILE}"${NC}' will be used?: "${UseConfig}""
        echo -e "#=========================================================================="
        echo -e "# Sourced '${LITTLE_BLUE}${CONFIG_FILE}${NC}'"
        echo -e "# To prevent further sourcing of this config file, delete it or empty it."
        echo -e "#=========================================================================="
        echo ""
    fi

    if [[ ${showConfig} == "showConfig" ]]; then
        echo -e "#================#"
        echo -e "# Current Config #"
        echo -e "#=============#=============================================================#"
        echo -e "# ${GRAY}### Remote path to mount${NC}"
        echo -e "# ${ORANGE}SOURCE${NC}=\"${SOURCE}\""
        echo -e "#"
        echo -e "# ${GRAY}### Local directory or mount the remote path to${NC}"
        echo -e "# ${ORANGE}DESTINATION${NC}=\"${DESTINATION}\""
        echo -e "#"
        echo -e "# ${GRAY}### Private key for SSH authentication${NC}"
        echo -e "# ${ORANGE}PRIVATE_KEY${NC}=\"${PRIVATE_KEY}\""
        echo -e "#"
        echo -e "# ${GRAY}### SSH Username on the remote device${NC}"
        echo -e "# ${ORANGE}USERNAME${NC}=\"${USERNAME}\""
        echo -e "#"
        echo -e "# ${GRAY}### Ip addresss or Hostname of the remote${NC}"
        echo -e "# ${ORANGE}HOSTNAME${NC}=\"${HOSTNAME}\""
        echo -e "#"
        echo -e "# ${GRAY}### SSH Port to use for connection${NC}"
        echo -e "# ${ORANGE}PORT${NC}=\"${PORT}\""
        echo -e "#"
        echo -e "# ${GRAY}### Enable bash script debugging (yes or no)${NC}"
        echo -e "# ${ORANGE}DEBUG${NC}=\"${DEBUG}\""
        echo -e "#"
        echo -e "# ${GRAY}### Timeout in seconds to wait for the remote host to respond (Network check)${NC}"
        echo -e "# ${ORANGE}NETWORK_TIMEOUT${NC}=${BLUE}${NETWORK_TIMEOUT}${NC}"
        echo -e "#"
        echo -e "# ${GRAY}### Automatically unmount after this many seconds (0 to disable)${NC}"
        echo -e "# ${ORANGE}MOUNT_TIMEOUT${NC}=${BLUE}${MOUNT_TIMEOUT}${NC}"
        echo -e "#"
        echo -e "# ${GRAY}### Set permission mode (e.g., 755) for the mount directory after mounting${NC}"
        echo -e "# ${ORANGE}DESTINATION_DIRECTORY_PERMISSION${NC}=${BLUE}${DESTINATION_DIRECTORY_PERMISSION}${NC}"
        echo -e "#"
        echo -e "# ${GRAY}### Additional SSH options (e.g., -oreconnect -oCompression)${NC}"
        echo -e "# ${ORANGE}SSH_OPTIONS${NC}=\"${SSH_OPTIONS}"\"
        echo -e "#"
        echo -e "#===========================================================================#"
        echo -e ""
    fi

    if [[ "${isunMounted}" -eq 1 ]]; then
        INFO "Successfully unmounted '${LITTLE_BLUE}${DESTINATION}${NC}'"
        [[ ${DestRemoved} -eq 1 ]] && {
            INFO "Removed '${LITTLE_BLUE}${DESTINATION}${NC}'"
        } || {
            ERROR "Failed to Remove '${LITTLE_BLUE}${DESTINATION}${NC}'" 1
        }
        echo ""
    fi

    if [[ "${isMounted}" -eq 1  ]]; then
        echo -e "#=================================================================================================================================="
        echo -e "# Mounted $(mount | grep "${DESTINATION}")" | grep --color=always -E "${USERNAME}|${HOSTNAME}"
        echo -e "#=================================================================================================================================="
        echo ""
        if [[ ${USERNAME} == u0_a* ]]; then
            ### Helping Messages
            echo -e "#============================================================================================="
            echo -e "# The termux default user home directory '${LITTLE_BLUE}${DESTINATION}/data/data/com.termux/files/home${NC}'"
            echo -e "# Phone's internal stroage filesystem '${LITTLE_BLUE}${DESTINATION}/storage/emulated/0/${NC}'"
            echo -e "#============================================================================================="
            echo ""
        fi
    fi
}

function EditConfig() {
    SetTextEditor # Set the terminal text editor
    if [[ ! -s "${CONFIG_FILE}" ]]; then
        echo -e "### Configuration File for SSHFS Mounting"                                        >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Remote path to mount"                                                         >> "${CONFIG_FILE}"
        echo -e "SOURCE=\"${SOURCE}\""                                                             >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Local directory or mount the remote path to"                                  >> "${CONFIG_FILE}"
        echo -e "DESTINATION=\"${DESTINATION}\""                                                   >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Private key for SSH authentication"                                           >> "${CONFIG_FILE}"
        echo -e "PRIVATE_KEY=\"${PRIVATE_KEY}\""                                                   >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### SSH Username on the remote device"                                            >> "${CONFIG_FILE}"
        echo -e "USERNAME=\"${USERNAME}\""                                                         >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Ip addresss or Hostname of the remote"                                        >> "${CONFIG_FILE}"
        echo -e "HOSTNAME=\"${HOSTNAME}\""                                                         >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### SSH Port to use for connection"                                               >> "${CONFIG_FILE}"
        echo -e "PORT=\"${PORT}\""                                                                 >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Enable bash script debugging (yes or no)"                                     >> "${CONFIG_FILE}"
        echo -e "DEBUG=\"${DEBUG}\""                                         >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Additional SSH options (e.g., -oreconnect -oCompression)"                     >> "${CONFIG_FILE}"
        echo -e "SSH_OPTIONS=\"${SSH_OPTIONS}"\"                                                   >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Timeout in seconds to wait for the remote host to respond (Network check)"    >> "${CONFIG_FILE}"
        echo -e "NETWORK_TIMEOUT=${NETWORK_TIMEOUT}"                                               >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Automatically unmount after this many seconds (0 to disable)"                 >> "${CONFIG_FILE}"
        echo -e "MOUNT_TIMEOUT=${MOUNT_TIMEOUT}"                                                   >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Set permission mode (e.g., 755) for the mount directory before mounting"      >> "${CONFIG_FILE}"
        echo -e "DESTINATION_DIRECTORY_PERMISSION=${DESTINATION_DIRECTORY_PERMISSION}"             >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "### Should this config file be used? (Yes or no)"                                 >> "${CONFIG_FILE}"
        echo -e "UseConfig=\"no\""                                                                 >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e ""                                                                                 >> "${CONFIG_FILE}"
        echo -e "# vim:filetype=sh"                                                                >> "${CONFIG_FILE}"
        ${EDITOR} "${CONFIG_FILE}"
        exit 0
    else
        ${EDITOR} "${CONFIG_FILE}"
        exit 0
    fi
}

### Check if the file exists and non-empty, if the variable UseConfig is set 'yes', then source it
if [[ -s "${CONFIG_FILE}" ]]; then
    ### Just export the UseConfig= variable value from config
    UseConfig=$(grep UseConfig "${CONFIG_FILE}" | cut -d'=' -f'2' | tr -d '"')
    export UseConfig
    if [[ "${UseConfig}" =~ ^(Yes|yes|true)$ ]]; then
        source "${CONFIG_FILE}"
    fi
    [[ "${DEBUG}" -eq 1 ]] && {
        DEBUG_LOG "UseConfig=$(grep UseConfig "${CONFIG_FILE}" | cut -d'=' -f'2' | tr -d '"')"
        DEBUG_LOG "export UseConfig\n"
    }

    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "source "${CONFIG_FILE}"\n"
fi

### If sshfs binary is not installed
if ! command -v sshfs  &> /dev/null; then
    ERROR "'${GREEN}sshfs${NC}' is not Installed, install it first using your package manager" 1
    InstallTool "sshfs"
fi

### Edit the config file
case "${FLAG}" in
    e|-e|--edit|edit)
        EditConfig
        ;;
    --debug)
        DEBUG=1
        ;;
esac

### Enable bash debugging
[[ ${DEBUG} -eq 1 ]] && {
    set -x
}

### Destination directory exists? unmount and remove it
if [[ -d "${DESTINATION}" ]]; then
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "timeout --signal KILL 4 fusermount -u "${DESTINATION}" 1> /dev/null 2>&1\n"
    timeout --signal KILL 4 fusermount -u "${DESTINATION}" 1> /dev/null 2>&1 && {
        isunMounted=1
    } || {
        ERROR "Un-mount failed on '${LITTLE_BLUE}${DESTINATION}${NC}'"
    }
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "rm -rf "${DESTINATION}" && DestRemoved=1\n"
    rm -rf "${DESTINATION}" && DestRemoved=1
    Log_Message "noConfig"
    exit 0
fi

### Before mounting check if host or IP is alive and listening
[[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "ping -c 1 -W ${NETWORK_TIMEOUT} ${HOSTNAME} &> /dev/null\n"
ping -c 1 -W ${NETWORK_TIMEOUT} ${HOSTNAME} &> /dev/null || {
    ERROR "'${LITTLE_BLUE}${HOSTNAME}${NC}' Not reachable, check the connection." 1
}

### Fully unset, If private is not set
if [[ ${PRIVATE_KEY} != "$HOME/.ssh" ]]; then
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "PRIVATE_KEY="-oIdentityFile=${PRIVATE_KEY}"\n"
    PRIVATE_KEY="-oIdentityFile=${PRIVATE_KEY}"
else
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "unset PRIVATE_KEY\n"
    unset PRIVATE_KEY
fi

if [[ -n ${PORT} ]]; then
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "PORT="-oPort=${PORT}"\n"
    PORT="-oPort=${PORT}"
else
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "unset PORT\n"
    unset PORT
fi

### Create destination directory
if [[ ! -d "${DESTINATION}" ]]; then
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "mkdir "${DESTINATION}" &> /dev/null"
    mkdir -p "${DESTINATION}" &> /dev/null || {
        ERROR "Cannot create '${LITTLE_BLUE}${DESTINATION}${NC}'" 1
    }
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "chmod ${DESTINATION_DIRECTORY_PERMISSION} "${DESTINATION}"\n"
    chmod ${DESTINATION_DIRECTORY_PERMISSION} "${DESTINATION}" && {
        permission_changed="yes" || permission_changed="no"
    }
fi

### Mount the remote or local device filesystem as a fuse.sshfs device using openssh protocal
[[ "${DEBUG}" -eq 1 ]]  && \
   DEBUG_LOG "timeout --signal KILL 8 sshfs ${PORT} ${PRIVATE_KEY} ${SSH_OPTIONS} "${USERNAME}@${HOSTNAME}:${SOURCE}" "${DESTINATION}"\n"
if timeout --signal KILL 8 sshfs ${PORT} ${PRIVATE_KEY} ${SSH_OPTIONS} "${USERNAME}@${HOSTNAME}:${SOURCE}" "${DESTINATION}"; then
    isMounted=1
        [[ ${permission_changed} != "yes" ]] && \
            ERROR "Cannot set permissions for '${LITTLE_BLUE}${DESTINATION}${NC}'" 0
    if [[ ${MOUNT_TIMEOUT} -ne 0 ]]; then
        (sleep ${MOUNT_TIMEOUT} && timeout --signal KILL 4 fusermount -u "${DESTINATION}") &
    fi
else
    [[ -d "${DESTINATION}" ]] && {
        [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "timeout --signal KILL 4 mountpoint -q "${DESTINATION}"\n"
        timeout --signal KILL 4 mountpoint -q "${DESTINATION}" && {
            [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "timeout --signal KILL 4 fusermount -u "${DESTINATION}" &> /dev/null\n"
            timeout --signal KILL 4 fusermount -u "${DESTINATION}" &> /dev/null
        }
    }
    [[ "${DEBUG}" -eq 1 ]] && DEBUG_LOG "rm -rf "${DESTINATION}"\n"
    rm -rf "${DESTINATION}"
    exit 1
fi

### Log the final messages
Log_Message "showConfig"

