#!/usr/bin/env bash

ARGS="$@"
PID_FILE="/tmp/.lastplayed_pid.backgroundPS"
LAST_PLAYED_TIME="$(date +%s)"
MPV_IPC_SEVER="/tmp/mpv_socket"

for arg in ${ARGS}; do
    if [[ -s ${PID_FILE} ]] || [[ ${arg} == "KILL" ]] ; then
        PID=$(cat "${PID_FILE}")
        kill -INT "${PID}" &> /dev/null
    fi
    mpv --loop --volume=65 --input-ipc-server="${MPV_IPC_SEVER}" ${arg} 1> /dev/null 2>&1 &
    [[ $? -eq 0 ]] && {
        PLAYED="$!"
        echo "${PLAYED}" 1> "${PID_FILE}"
    }
    ### One song at a time
    exit 0
done

