#!/bin/bash

MUSIC_DIRECTORY="$HOME/Music"
SELECTED=$(ls "${MUSIC_DIRECTORY}" | grep -i -E ".mp3|.wav|.flac" | fzf)
GREEN="\033[38;2;80;250;100m"
BROWN="\033[38;2;240;120;120m"
GREY="\033[38;2;160;160;140m"
BLUE="\033[38;2;150;134;255m"
NC="\033[0m"

if [[ -n ${SELECTED} ]]; then
    echo -e "${GREY}MUSIC${NC}: ${GREEN}${SELECTED}${NC}"
    echo -e "${GREY}COMMAND${NC}: ${BROWN}mpv${NC} --loop --no-video --volume=65 \"${BLUE}${MUSIC_DIRECTORY}/${SELECTED}${NC}\""
    echo -e ""
    mpv --loop --no-video --volume=64 "${MUSIC_DIRECTORY}/${SELECTED}"
else
    echo "No song selected"
fi

