#!/bin/bash

DEST="$HOME/proton_drive"
SOURCE="ProtonDrive"

LITTLE_BLUE="\033[38;2;126;117;255m"
RED="\033[38;2;200;10;10m"
NO_COL="\033[0m"

test -d "${DEST}" || mkdir -p "${DEST}"

if mountpoint -q "${DEST}"; then
    fusermount -u "${DEST}" && echo -e "Successfully unmounted '${LITTLE_BLUE}${DEST}${NO_COL}'"
    exit 0
fi

rclone mount --vfs-cache-mode writes --ignore-existing --delete-during --links --daemon ${SOURCE}:/ "${DEST}" && \
    echo "Mounted $(mount | grep ${SOURCE})" || echo "[${RED}ERROR${NO_COL}]: Mount failed"

