#!/bin/bash

EDITOR="$1"
FILE="$HOME/Notes/Language/Spanish/Lesson_$(( $(date +%s)/86400 - 20152))_$(date +%d-%b-%Y_).md"
GREEN="\033[38;2;10;244;10m"
NC="\033[0m"

if [[ -n "$EDITOR" ]]; then
    command -v "$EDITOR" > /dev/null 2>&1
    [[ $? -ne 0 ]] && EDITOR="${EDITOR:-"vim"}"
    if [[ ! -s "${FILE}" ]]; then # -s if the file exist and not empty
        echo "File does not exist"
    fi
    "${EDITOR}" "${FILE}"
    exit 0
fi

if [[ ! -f "${FILE}" ]]; then
    touch "${FILE}"
    echo -e "Created ${GREEN}${FILE}${NC}"
else
    echo -e "File already exists: ${GREEN}${FILE}${NC}"
fi

