#!/bin/bash

[[ $1 == "clear" ]] && clear

result=$(systemctl is-active docker.service 2> /dev/null)

if [[ $result == "inactive" ]] ; then
    sudo systemctl start docker.service
fi

docker start Ubuntu
docker exec -it Ubuntu bash -c 'cd ~ && exec bash'

