#!/bin/bash

result=$(systemctl is-active docker 2> /dev/null)

[[ "${result}" == "inactive" ]] && {
    sudo systemctl start docker
}

docker start Ubuntu

[[ $1 =~ ^(clear|cls|cl|c)$ ]] && clear

docker exec -it Ubuntu bash -c 'cd ~ && exec bash'

